# Generated by Django 2.2.7 on 2019-11-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
